Third Eye and Utsusemi should not stack.
topaz-next/topaz pull request #2563
Opened 2021-02-02 14:47 UTC by gweivyth

**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

![image](https://user-images.githubusercontent.com/37130689/106616443-914ab400-653b-11eb-84a5-b9befb3eecb2.png)

Above image taken from retail.  These effects shouldn't stack.  Copy Image should wipe Third Eye, and Third Eye should have no effect when player is under the effect of Copy Image.

2021-02-03 07:34 UTC, Xaver-DaRed commented
Tabs need to be converted to 4 spaces/formating, in general.
I would also edit utsusemi_san, becouse theres no reason for it not removing third eye aswell if ichi and ni do.
Sent you a DM to discord with the formated files

2021-02-03 18:46 UTC, gweivyth commented
I totally blanked on San even existing cause of 75-brain, added the formatting you sent and the update for San as well, thanks!

2021-02-03 23:35 UTC, claywar requested changes

2021-02-03 23:35 UTC, claywar commented on scripts/globals/spells/utsusemi_ichi.lua
> +    and target:delStatusEffect(67) -- Third Eye and Utsusemi don't stack.  Utsusemi removes Third Eye.
Is there an equivalent status effect for this?  Magic numbers.

2021-02-03 23:35 UTC, claywar commented on scripts/globals/spells/utsusemi_ni.lua
> +    and target:delStatusEffect(67) -- Third Eye and Utsusemi don't stack.  Utsusemi removes Third Eye.
Same as above, magic numbers.

2021-02-03 23:35 UTC, claywar commented on scripts/globals/spells/utsusemi_san.lua
> +    and target:delStatusEffect(67) -- Third Eye and Utsusemi don't stack.  Utsusemi removes Third Eye.
Same as above, magic numbers.

2021-02-04 06:26 UTC, zach2good commented
Is checking for `tpz.effect.COPY_IMAGE` enough? I say this because on retail when my gearswap checks for and cancels shadows, I have to check for 4 things: 
```lua
    -- Cancel Shadows
	if spell.english == "Utsusemi: Ichi" then
		if buffactive['Copy Image'] then
			send_command('@wait 2.2; cancel 66')
		elseif buffactive['Copy Image (2)'] then 
			send_command('@wait 2.2; cancel 444')
		elseif buffactive['Copy Image (3)'] then
			send_command('@wait 2.2; cancel 445')
		elseif buffactive['Copy Image (4+)'] then
			send_command('@wait 2.2; cancel 446')
		end
    end
```

2021-02-04 06:30 UTC, zach2good commented on scripts/globals/spells/utsusemi_ichi.lua
> +    and target:delStatusEffect(67) -- Third Eye and Utsusemi don't stack.  Utsusemi removes Third Eye.
This section will resolve to `local effect = target:getStatusEffect(tpz.effect.COPY_IMAGE) and target:delStatusEffect(67)`, making effect a bool (I think). Is that your intention?

Or should the `and` be removed?
```lua
local effect = target:getStatusEffect(tpz.effect.COPY_IMAGE)
target:delStatusEffect(67) -- Third Eye and Utsusemi don't stack.  Utsusemi removes Third Eye.
```

2021-02-04 06:53 UTC, Xaver-DaRed commented on scripts/globals/abilities/third_eye.lua
> +        player:addStatusEffect(tpxz.effect.THIRD_EYE, 0, 0, 30) --power keeps track of procs
Typo in this line. tpxz should be changed to tpz

2021-02-05 21:34 UTC, TeoTwawki commented
> 
> 
> **EDIT:** Ah, yes, I can read. Ignore everything below. Third eye is the thing being cancelled!
> 
> Is checking for `tpz.effect.COPY_IMAGE` enough? I say this because on retail when my gearswap checks for and cancels shadows, I have to check for 4 things:
> 
> ```lua
>     -- Cancel Shadows
> 	if spell.english == "Utsusemi: Ichi" then
> 		if buffactive['Copy Image'] then
> 			send_command('@wait 2.2; cancel 66')
> 		elseif buffactive['Copy Image (2)'] then 
> 			send_command('@wait 2.2; cancel 444')
> 		elseif buffactive['Copy Image (3)'] then
> 			send_command('@wait 2.2; cancel 445')
> 		elseif buffactive['Copy Image (4+)'] then
> 			send_command('@wait 2.2; cancel 446')
> 		end
>     end
> ```

I believe the old ones cheated and used `effect:setIcon()` to use just one effect in reality while sending the correct effectID packets to the client to set the correct icon and tell the client "its multiple effects, honest!" in a similar manner to if we had used `addStatusEffectEx()`.

2021-02-05 21:38 UTC, TeoTwawki commented on scripts/globals/abilities/third_eye.lua
> +    if (player:hasStatusEffect(tpz.effect.COPY_IMAGE)) then
outermost parenthesis are not required. you should use parenthesis on things that are functions like `addStatusEffect()` needs them, or to clarify order of operations like `if a and (b or c) and d then`

So here you would want
```lua
 if player:hasStatusEffect(tpz.effect.COPY_IMAGE) then
```

2021-02-05 21:41 UTC, TeoTwawki commented
> Final commit. 

Allegedly! :wink: 

jokes aside safest to be descriptive even on short quick fixes, unless you intend to squash after.

2021-02-06 12:04 UTC, zach2good commented
The content is there, but the formatting is off. I'll merge this into a branch and clean it up, then yeet it into release. Thanks for the contribution 👍

2021-02-06 12:06 UTC, merged